#!/bin/bash

# Get the current directory
current_dir=$(pwd)

# Convert PATH into an array of directories
IFS=':' read -ra dirs_in_path <<< "$PATH"

# Check if current directory is in PATH
for dir in "${dirs_in_path[@]}"; do
    if [ "$dir" = "$current_dir" ]; then
        printf "\033[1;32mCurrent directory is in the PATH\033[0m\n"
        exit 0
    fi
done

printf "\033[1;31mCurrent directory is not in the PATH\033[0m\n"
