#!/bin/bash 

# Filename: ghcix
# Description: Launches the ghcci compiler with the last edited haskell file as the source
# Author: OshDubh

last_file=$(ls -rt *.hs | tail -1)
ghc -o ${last_file%.*} $last_file
./${last_file%.*}

rm $last_file.o $lastfile.hi