#!/bin/bash
# if we get an arg, use that
[[ -n $1 ]] && go mod init $1 && exit 0

# check if in a git repo
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo -e "no module name provided, not in a git repo\nusage:\n\tgomodinit <module name>\n\tgomodinit [if inside a git repo. this will use the git remote url normalised, and the relative path from the root git dir to create it, e.g. github.com/OshDubh/bash-scraps/a_sub_project]" >&2
    exit 1
fi

# get remote details
username=$(git config user.email | cut -d'@' -f1)
origin=$(git remote -v | grep "fetch" | sed -e 's|origin||' -e 's|git@||' -e 's|\.git||' -e 's|(fetch)||' -e 's|:|/|' | xargs)
[[ "$(basename origin)" == "$(basename $PWD)" ]] && go mod init $origin && exit 0

# if we're not a base folder, append the rest
get_dir_diff() {
    local match="$1"
    local dir="${2:-$PWD}"
    local diff=""

    while [[ "$dir" != "/" ]]; do
        if [[ "$(basename "$dir")" == *"$match"* ]]; then
            printf ${diff%?} # less the last trailing slash
            return 0
        fi
        diff="$(basename $dir)/$diff"
        dir=$(dirname "$dir")
    done

    return 1
}

go mod init "$origin/$(get_dir_diff $(basename $origin))"
