#!/bin/bash

# Filename: last_modified
# Description: Changes the "last modified" line in a file whenever it is saved
# Author: OshDubh

# function name: get_date_time
# description: Takes a file and returns the full desired date format
get_date_time () {
  local input_file="$1" # get save the file name
  local day=$(date -r $input_file +%d) # get the day number from the timestamp
  local suffix="th" # default suffix

  # change for special cases
  if [[ "$day" != 11 && "$day" != 12 && "$day" != 13 ]]; then
    case ${day: -1} in # get the last digit of the day number
      1) suffix="st";;
      2) suffix="nd";;
      3) suffix="rd";;
    esac
  fi

  echo $(date -r $input_file +"%R on %A, the %d$suffix of %B, %Y.")
}

# funciton name: program
# description: the main loop that constantly runs
program ()
{
    # get the info we need
    file="$1" 
    
    suffix=$(echo $file | sed -e 's|^\(.*\.\)||g')  # get the last modified file's file extension
    script_location=$(dirname "$0")  # get the location of the script

    # exit if there is no template for the file
    [[ -f "$script_location/template_$suffix.txt" ]] || echo "No template exists for the last modified file." || exit

    # intelligently get what line we need to modify from the template
    line=$(cat "$script_location/template_$suffix.txt" | grep "_last_modified_" | sed -e 's|_last_modified_||g' ) # get everything before the match in the line
    [[ -z "$line" ]] && echo "The template for the last modified file does not have a _last_modified_ line." && exit # exit if there is no _last_modified_ line

    # only modify the line if the current line is older than the one derived from the modification time of the file
    current_last_modified_line=$(cat "$file" | grep "$line") # get the current last modified line that exists in the file
    new_last_modified_line="$line$(get_date_time $file)" # what the line should say

    # replace the line if they're not equal
    if [[ "$current_last_modified_line" != "$new_last_modified_line" ]]
    then
      sed -i"._lmbackup.$(date +%s).txt" "s|$current_last_modified_line|$new_last_modified_line|" "$file"
      mv ./*._lmbackup.*.txt $(dirname "$0")
      echo "updated $file to $new_last_modified_line"
    fi
}

input_file="$1" # get the file from the cli
[[ -z "$input_file" ]] && input_file=$(ls -t | head -n 1) # get the last modified file if none is given
echo "watching: $input_file"

modified=$(date -r $input_file +%s)

while true;
do
  if [[ "$modified" -ne $(date -r $input_file +%s) ]];
  then
    program "$input_file"
  fi
  modified=$(date -r $input_file +%s)
  sleep 1
done
