#!/bin/bash

# variable initilisation
# Command syntax:
# subl_create [filename] "[description]"
# supports c and python

# extract information from the filename
filename="$1" # the filename, including suffix
language=$(echo $filename | sed -e 's|^\(.*\.\)||g') # the file suffix (everything after the ".")
title=$(echo $filename | sed -e 's|\.[^.]*$||g') # the filename without the suffix or the "."

# get the right suffix for the date
DaySuffix() {
  case `date +%d` in
    01|21|31) echo "st";;
    02|22)    echo "nd";;
    03|23)    echo "rd";;
    *)       echo "th";;
  esac
}

#format the date
today=$(date +"Date created: %R on %A, the %d`DaySuffix` of %B, %Y.") # All other dates

touch "$filename" # create the file

# Fill the file with the right stuff for the right file
cat ~/bin/${language}_template.txt >> $filename

# replace the template variables with the actual variables
sed -i "s|_filename_|$filename|g" $filename
sed -i "s|_title_|$title|g" $filename
sed -i "s|_description_|$2|g" $filename
sed -i "s|_user_|$USER|g" $filename
sed -i "s|_date_|$today|g" $filename

# open the file in sublime
subl "$filename"
